version: '3.8'

services:
  app:
    image: "ns927guideline/adherence_app:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - predictive_model
    environment:
      - DATABASE_URL=mysql+pymysql://nico:password@db:3306/adherence_db
      - PREDICTIVE_MODEL=http://predictive_model:5001

  db:
    build: ./mysql_custom
    environment:
      MYSQL_USER: nico
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: adherence_db
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  predictive_model:
    image: "ns927guideline/adherence_model:latest"
    ports:
      - "5001:5001"

volumes:
  db_data:
